package br.com.senac.portifolio;

import java.text.DecimalFormat;

/**
 * CRIAÇÃO DE UMA CALCULADORA ARITMETICA CONTENDO AS QUATRO OPERAÇÕES
 * MATEMÁTICAS
 * @author https://github.com/santthiago
 */
public class CalcAritmetica extends javax.swing.JFrame {

    private void somar() {
        DecimalFormat formatador = new DecimalFormat("0.00");
        double n1, n2, resultado;
        n1 = Double.parseDouble(txtNum1.getText().replace(",", "."));
        n2 = Double.parseDouble(txtNum2.getText().replace(",", "."));
        resultado = n1 + n2;
        txtResultado.setText(formatador.format(resultado));

    }

    private void subtrair() {
        DecimalFormat formatador = new DecimalFormat("0.00");
        double n1, n2, resultado;
        n1 = Double.parseDouble(txtNum1.getText().replace(",", "."));
        n2 = Double.parseDouble(txtNum2.getText().replace(",", "."));
        resultado = n1 - n2;
        txtResultado.setText(formatador.format(resultado));
    }

    private void multiplicar() {
        DecimalFormat formatador = new DecimalFormat("0.00");
        double n1, n2, resultado;
        n1 = Double.parseDouble(txtNum1.getText().replace(",", "."));
        n2 = Double.parseDouble(txtNum2.getText().replace(",", "."));
        resultado = n1 * n2;
        txtResultado.setText(formatador.format(resultado));
    }

    private void dividir() {
        DecimalFormat formatador = new DecimalFormat("0.00");
        double n1, n2, resultado;
        n1 = Double.parseDouble(txtNum1.getText().replace(",", "."));
        n2 = Double.parseDouble(txtNum2.getText().replace(",", "."));
        resultado = n1 / n2;
        txtResultado.setText(formatador.format(resultado));
    }
    
    private void limpar(){
        txtResultado.setText("__resultado__");
        txtNum1.setText("");
        txtNum2.setText("");
        
   }

    /**
     *
     */
    public CalcAritmetica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNum1 = new javax.swing.JTextField();
        txtNum2 = new javax.swing.JTextField();
        txtResultado = new javax.swing.JTextField();
        btnSubtrair = new javax.swing.JButton();
        btnMultiplicar = new javax.swing.JButton();
        btnSomar = new javax.swing.JButton();
        btnDividir = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CALCULADORA ARITMÉTICA");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("N.1º");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 40, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("N.2º");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 50, 30));

        txtNum1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNum1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtNum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 60, 40));

        txtNum2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNum2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtNum2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 70, 40));

        txtResultado.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtResultado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtResultado.setText("__resultado__");
        getContentPane().add(txtResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 240, 58));

        btnSubtrair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/icones/calc.art_subtração.png"))); // NOI18N
        btnSubtrair.setToolTipText("SUBTRAIR");
        btnSubtrair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubtrairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubtrair, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 95, 95));

        btnMultiplicar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/icones/calc.art_multiplicação.png"))); // NOI18N
        btnMultiplicar.setToolTipText("MULTIPLICAR");
        btnMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicarActionPerformed(evt);
            }
        });
        getContentPane().add(btnMultiplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 95, 95));

        btnSomar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/icones/calc.art_adição.png"))); // NOI18N
        btnSomar.setToolTipText("SOMAR");
        btnSomar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSomarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSomar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 95, 95));

        btnDividir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/icones/calc.art_divisao.png"))); // NOI18N
        btnDividir.setToolTipText("DIVIDIR");
        btnDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDividirActionPerformed(evt);
            }
        });
        getContentPane().add(btnDividir, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 95, 95));

        btnLimpar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLimpar.setText("C");
        btnLimpar.setToolTipText("LIMPAR");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, -1, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/icones/calc.art_modelo.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 440));

        setSize(new java.awt.Dimension(437, 480));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicarActionPerformed
        //chamando o  metodo
        multiplicar();
    }//GEN-LAST:event_btnMultiplicarActionPerformed

    private void btnSomarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSomarActionPerformed
        //chamando o  metodo
        somar();
    }//GEN-LAST:event_btnSomarActionPerformed

    private void btnSubtrairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubtrairActionPerformed
        // chamando o metodo
        subtrair();
    }//GEN-LAST:event_btnSubtrairActionPerformed

    private void btnDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDividirActionPerformed
        // chamando o metodo
        dividir();
    }//GEN-LAST:event_btnDividirActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // chamando o metodo 
        limpar();
    }//GEN-LAST:event_btnLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalcAritmetica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalcAritmetica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalcAritmetica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalcAritmetica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalcAritmetica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDividir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnMultiplicar;
    private javax.swing.JButton btnSomar;
    private javax.swing.JButton btnSubtrair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtNum1;
    private javax.swing.JTextField txtNum2;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables
}
