package br.com.senac.portifolio;

/**
 * Criação de um portifólio interativo, contendo 10 aplicações distintas
 *
 * @author https://github.com/santthiago
 */
public class GuiaInterativa extends javax.swing.JFrame {

    /**
     *
     */
    public GuiaInterativa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCalculoMediaImc = new javax.swing.JButton();
        btnCalcCombustivel = new javax.swing.JButton();
        btnCalcBimestre = new javax.swing.JButton();
        btnConversorMonetario = new javax.swing.JButton();
        btnTabuada = new javax.swing.JButton();
        btnJokenpo = new javax.swing.JButton();
        btnDado = new javax.swing.JButton();
        btnCalculadoraAritmetica = new javax.swing.JButton();
        btnJogoBaralho = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GUIA INTERATIVA");
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setResizable(false);

        btnCalculoMediaImc.setBackground(new java.awt.Color(204, 204, 255));
        btnCalculoMediaImc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/icones/imc_app.png"))); // NOI18N
        btnCalculoMediaImc.setToolTipText("CALCULADORA IMC");
        btnCalculoMediaImc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculoMediaImcActionPerformed(evt);
            }
        });

        btnCalcCombustivel.setBackground(new java.awt.Color(255, 255, 204));
        btnCalcCombustivel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/icones/combustivel_app.png"))); // NOI18N
        btnCalcCombustivel.setToolTipText("CALCULADORA DE COMBUSTIVEL");
        btnCalcCombustivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcCombustivelActionPerformed(evt);
            }
        });

        btnCalcBimestre.setBackground(new java.awt.Color(255, 102, 102));
        btnCalcBimestre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/icones/notabimestral_app.png"))); // NOI18N
        btnCalcBimestre.setToolTipText("CALCULADORA DE NOTAS BIMESTRAIS");
        btnCalcBimestre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcBimestreActionPerformed(evt);
            }
        });

        btnConversorMonetario.setBackground(new java.awt.Color(255, 255, 255));
        btnConversorMonetario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/icones/conv.moeda_app.png"))); // NOI18N
        btnConversorMonetario.setToolTipText("CONVERSOR DE MOEDAS (REAIS R$ / DOLARES R$)");
        btnConversorMonetario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConversorMonetarioActionPerformed(evt);
            }
        });

        btnTabuada.setBackground(new java.awt.Color(255, 204, 204));
        btnTabuada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/icones/tabuada_app.png"))); // NOI18N
        btnTabuada.setToolTipText("TABUADA");
        btnTabuada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTabuadaActionPerformed(evt);
            }
        });

        btnJokenpo.setBackground(new java.awt.Color(255, 204, 0));
        btnJokenpo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/icones/jokenpo_app.png"))); // NOI18N
        btnJokenpo.setToolTipText("JOGO JOKENPÔ");
        btnJokenpo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJokenpoActionPerformed(evt);
            }
        });

        btnDado.setBackground(new java.awt.Color(102, 255, 255));
        btnDado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/icones/dado_app.png"))); // NOI18N
        btnDado.setToolTipText("JOGO DO DADO");
        btnDado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDadoActionPerformed(evt);
            }
        });

        btnCalculadoraAritmetica.setBackground(new java.awt.Color(102, 255, 204));
        btnCalculadoraAritmetica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/icones/calc.art_app.png"))); // NOI18N
        btnCalculadoraAritmetica.setToolTipText("CALCULADORA ARITMÉTICA");
        btnCalculadoraAritmetica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculadoraAritmeticaActionPerformed(evt);
            }
        });

        btnJogoBaralho.setBackground(new java.awt.Color(204, 255, 204));
        btnJogoBaralho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/icones/baralho_app.png"))); // NOI18N
        btnJogoBaralho.setToolTipText("JOGO DE CARTAS");
        btnJogoBaralho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJogoBaralhoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCalcBimestre, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCalculoMediaImc, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCalcCombustivel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnJokenpo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTabuada, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDado, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnConversorMonetario, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnJogoBaralho, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCalculadoraAritmetica, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCalcBimestre, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalculoMediaImc, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcCombustivel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnJokenpo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTabuada, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDado, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConversorMonetario, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnJogoBaralho, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalculadoraAritmetica, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        setSize(new java.awt.Dimension(422, 424));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalculoMediaImcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculoMediaImcActionPerformed
        CalculadoraImc calculoimc = new CalculadoraImc();
        calculoimc.setVisible(true);
    }//GEN-LAST:event_btnCalculoMediaImcActionPerformed

    private void btnCalcCombustivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcCombustivelActionPerformed
        AlcXGas calculadora = new AlcXGas();
        calculadora.setVisible(true);
    }//GEN-LAST:event_btnCalcCombustivelActionPerformed

    private void btnConversorMonetarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConversorMonetarioActionPerformed
        ConversorDeMoeda conversor = new ConversorDeMoeda();
        conversor.setVisible(true);
    }//GEN-LAST:event_btnConversorMonetarioActionPerformed

    private void btnCalcBimestreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcBimestreActionPerformed
        CalculadoraBimestral calculadora = new CalculadoraBimestral();
        calculadora.setVisible(true);
    }//GEN-LAST:event_btnCalcBimestreActionPerformed

    private void btnTabuadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTabuadaActionPerformed
        Tabuada calculadora = new Tabuada();
        calculadora.setVisible(true);
    }//GEN-LAST:event_btnTabuadaActionPerformed

    private void btnJokenpoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJokenpoActionPerformed
        Jokenpo jogo = new Jokenpo();
        jogo.setVisible(true);
    }//GEN-LAST:event_btnJokenpoActionPerformed

    private void btnDadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDadoActionPerformed
        JogoDoDado jogo = new JogoDoDado();
        jogo.setVisible(true);
    }//GEN-LAST:event_btnDadoActionPerformed

    private void btnCalculadoraAritmeticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculadoraAritmeticaActionPerformed
        CalcAritmetica calculadora = new CalcAritmetica();
        calculadora.setVisible(true);
    }//GEN-LAST:event_btnCalculadoraAritmeticaActionPerformed

    private void btnJogoBaralhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJogoBaralhoActionPerformed
        JogoDasCartas jogo = new JogoDasCartas();
        jogo.setVisible(true);
    }//GEN-LAST:event_btnJogoBaralhoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiaInterativa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiaInterativa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiaInterativa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiaInterativa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiaInterativa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcBimestre;
    private javax.swing.JButton btnCalcCombustivel;
    private javax.swing.JButton btnCalculadoraAritmetica;
    private javax.swing.JButton btnCalculoMediaImc;
    private javax.swing.JButton btnConversorMonetario;
    private javax.swing.JButton btnDado;
    private javax.swing.JButton btnJogoBaralho;
    private javax.swing.JButton btnJokenpo;
    private javax.swing.JButton btnTabuada;
    // End of variables declaration//GEN-END:variables

}
