package br.com.senac.portifolio;

/**
 * CRIAÇÃO DE UMA ESTRUTURA RANDOMICA PARA SELEÇÃO DE UMA FACE DO DADO
 *
 * @author https://github.com/santthiago
 */
public class JogoDoDado extends javax.swing.JFrame {

    /**
     *
     */
    public void jogar() {
        int dado = (int) (Math.random() * 6 + 1);
        System.out.println("" + dado);
        switch (dado) {
            case 1:
                lblDado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/icones/dado_face_1.png")));
                break;
            case 2:
                lblDado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/icones/dado_face_2.png")));
                break;
            case 3:
                lblDado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/icones/dado_face_3.png")));
                break;
            case 4:
                lblDado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/icones/dado_face_4.png")));
                break;
            case 5:
                lblDado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/icones/dado_face_5.png")));
                break;
            case 6:
                lblDado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/icones/dado_face_6.png")));
                break;
            default:
                break;
        }
    }

    /**
     * Creates new form JogoDoDado
     */
    public JogoDoDado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDado = new javax.swing.JLabel();
        btnLancarDado = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("JOGO DO DADO");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/icones/dados_festa.jpg"))); // NOI18N
        getContentPane().add(lblDado, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 250, 260));

        btnLancarDado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/icones/dados_lançar.png"))); // NOI18N
        btnLancarDado.setToolTipText("LANÇAR O DADO");
        btnLancarDado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLancarDadoActionPerformed(evt);
            }
        });
        getContentPane().add(btnLancarDado, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, 130, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/senac/icones/dado_base.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 490));

        setSize(new java.awt.Dimension(567, 530));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLancarDadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLancarDadoActionPerformed
        // TODO add your handling code here:
        jogar();
    }//GEN-LAST:event_btnLancarDadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JogoDoDado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JogoDoDado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JogoDoDado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JogoDoDado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JogoDoDado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLancarDado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblDado;
    // End of variables declaration//GEN-END:variables
}
